### ISSUE TITLE
Classcast exception is thrown for nonlocatable Run Configurations

### ISSUE THREAD

**Issue by novotnyr** [krasa/MavenHelper#36]
My custom plugin uses a _Run Configuration_ that does not implement `LocatableConfiguration`. Sadly, this makes Maven Helper plugin unhappy, throwing an exception.

```
update failed for ActionGroup: Test file (Run current File with Maven)[Test file]

java.lang.ClassCastException: com.github.novotnyr.idea.rabbitmq.RabbitMqScriptRunConfiguration cannot be cast to com.intellij.execution.configurations.LocatableConfiguration
	at krasa.mavenhelper.action.RunTestFileAction.update(RunTestFileAction.java:202)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareUpdate(ActionUtil.java:171)
	at com.intellij.openapi.actionSystem.impl.Utils.doUpdate(Utils.java:256)
	at com.intellij.openapi.actionSystem.impl.Utils.updateGroupChild(Utils.java:333)
	at com.intellij.openapi.actionSystem.impl.Utils.hasChildrenWithState(Utils.java:307)
```
Looking into source code of the `RunTestFileAction`, there is an explicit cast that might not always be correct.

**Comment by krasa** [comment]
Try this: [MavenRunHelper.zip](https://github.com/krasa/MavenHelper/files/2585811/MavenRunHelper.zip)

**Comment by novotnyr** [comment]
Looks good, thanks for superquick fix!
