### ISSUE TITLE
exclude leads to Pom file not found

### ISSUE THREAD

**Issue by StephanPraetsch** [krasa/MavenHelper#55]
Hi,

if I want to exclude a maven dependency I get an error "Pom file not found"

For instance I want to exclude `commons-logging` from [spring3-mvc-maven-xml-hello-world](https://github.com/mkyong/spring3-mvc-maven-xml-hello-world)
![pom-file-not-found](https://user-images.githubusercontent.com/9827763/83008760-fb5aa300-a015-11ea-9c90-94cbc98f5cd2.png)

Futhermore I cannot remove a dependency like `spring-webmvc`. There is no information displayed and nothing happens at all.

I'm using
```
IntelliJ IDEA 2020.1.1 (Ultimate Edition)
Build #IU-201.7223.91, built on April 30, 2020
Runtime version: 11.0.6+8-b765.40 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.15.0-101-generic
GC: ParNew, ConcurrentMarkSweep
Memory: 10173M
Cores: 8
Non-Bundled Plugins: Key Promoter X, MoreUnit, PlantUML integration, EclipseCodeFormatter, Lombook Plugin, com.kukido.eclipser, MavenRunHelper, BashSupport, org.jetbrains.kotlin, kotlintest-plugin-intellij, com.intellij.lang.jsgraphql, com.wix.eslint, intellij.prettierJS, org.asciidoctor.intellij.asciidoc, org.mule.tooling.intellij.raml
Current Desktop: ubuntu:GNOME
```
and `Maven Helper` in version 4.7.193.000.0

**Comment by krasa** [comment]
Works fine for me, maybe Linux has something to do with it.
Is that project located in some kind of virtual folder, symlink...?

```
IntelliJ IDEA 2020.1.2 (Community Edition)
Build #IC-201.7846.53, built on May 26, 2020
Runtime version: 11.0.7+10-b765.53 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 725M
Cores: 4
Registry: new.search.everywhere=false
Non-Bundled Plugins: MavenRunHelper
```

**Comment by krasa** [comment]
Does it work using IntelliJ's Maven Dependencies Diagram?

**Comment by StephanPraetsch** [comment]
Neither that project nor idea are located in a virtual folder.
Which plugin provides Maven Dependencies Diagram? Obviously I haven't installed it yet. Is it `Maven Dependency Manager`?

**Comment by krasa** [comment]
https://www.jetbrains.com/help/idea/work-with-maven-dependencies.html#pom_see_diagram

**Comment by StephanPraetsch** [comment]
Ah, ok. Yes that works
![image](https://user-images.githubusercontent.com/9827763/83060663-20720480-a05c-11ea-9ba4-acec320ee34e.png)

**Comment by StephanPraetsch** [comment]
By the way `Jump To Source` doesn't work as well. It just happens nothing.

**Comment by krasa** [comment]
I added some error logging... Could you try it? Just drag it into the editor
[MavenRunHelper.zip](https://github.com/krasa/MavenHelper/files/4691540/MavenRunHelper.zip)

**Comment by StephanPraetsch** [comment]
Ok, I did. Installed is Maven Helper 4.8.193.000.0.
Where do I find the error logging? The popup and Event Log still only shows "Pom file not found".

**Comment by krasa** [comment]
It should pop up like any other IDE error. Or just `Help | Show log in explorer`.
I installed Ubuntu in virtual, all your plugins but still can't reproduce it. :(

**Comment by StephanPraetsch** [comment]
I don't find any logs concerning MavenHelper:
![image](https://user-images.githubusercontent.com/9827763/83280398-e2e5b680-a1d6-11ea-9c1e-71dd94a0911b.png)
```
stephan@lin-praetschs:~/.cache/JetBrains/IntelliJIdea2020.1/log> grep MavenHelper *log*
grep: build-log: Is a directory
stephan@lin-praetschs:~/.cache/JetBrains/IntelliJIdea2020.1/log> 
```
Is 4.8.193.000.0 the correct version with the extended log?

**Comment by krasa** [comment]
Yes, maybe the problem was somewhere else... I added even more logging. 
[MavenRunHelper.zip](https://github.com/krasa/MavenHelper/files/4703643/MavenRunHelper.zip)

Some stacktrace should be in `idea.log`

like:
```
2020-05-29 20:27:41,543 [   9625]  ERROR - nSystem.impl.ActionManagerImpl - IntelliJ IDEA 2020.2 EAP  Build #IU-202.4357.23 
2020-05-29 20:27:41,543 [   9625]  ERROR - nSystem.impl.ActionManagerImpl - JDK: 11.0.3; VM: Java HotSpot(TM) 64-Bit Server VM; Vendor: Oracle Corporation 
2020-05-29 20:27:41,543 [   9625]  ERROR - nSystem.impl.ActionManagerImpl - OS: Windows 10 
2020-05-29 20:28:13,036 [  41118]  ERROR - per.analyzer.action.BaseAction - XmlFile null for virtualFile=null; artifact=org.springframework:spring-webmvc:jar:3.2.13.RELEASE->(org.springframework:spring-beans:jar:3.2.13.RELEASE->(org.springframework:spring-core:jar:3.2.13.RELEASE[DUPLICATE:org.springframework:spring-core:jar:3.2.13.RELEASE]->()),org.springframework:spring-context:jar:3.2.13.RELEASE->(org.springframework:spring-aop:jar:3.2.13.RELEASE->(aopalliance:aopalliance:jar:1.0->(),org.springframework:spring-beans:jar:3.2.13.RELEASE[DUPLICATE:org.springframework:spring-beans:jar:3.2.13.RELEASE]->(),org.springframework:spring-core:jar:3.2.13.RELEASE[DUPLICATE:org.springframework:spring-core:jar:3.2.13.RELEASE]->()),org.springframework:spring-beans:jar:3.2.13.RELEASE[DUPLICATE:org.springframework:spring-beans:jar:3.2.13.RELEASE]->(),org.springframework:spring-core:jar:3.2.13.RELEASE[DUPLICATE:org.springframework:spring-core:jar:3.2.13.RELEASE]->(),org.springframework:spring-expression:jar:3.2.13.RELEASE[DUPLICATE:org.springframework:spring-expression:jar:3.2.13.RELEASE]->()),org.springframework:spring-core:jar:3.2.13.RELEASE->(),org.springframework:spring-expression:jar:3.2.13.RELEASE->(org.springframework:spring-core:jar:3.2.13.RELEASE[DUPLICATE:org.springframework:spring-core:jar:3.2.13.RELEASE]->()),org.springframework:spring-web:jar:3.2.13.RELEASE->(org.springframework:spring-aop:jar:3.2.13.RELEASE[DUPLICATE:org.springframework:spring-aop:jar:3.2.13.RELEASE]->(),org.springframework:spring-beans:jar:3.2.13.RELEASE[DUPLICATE:org.springframework:spring-beans:jar:3.2.13.RELEASE]->(),org.springframework:spring-context:jar:3.2.13.RELEASE[DUPLICATE:org.springframework:spring-context:jar:3.2.13.RELEASE]->(),org.springframework:spring-core:jar:3.2.13.RELEASE[DUPLICATE:org.springframework:spring-core:jar:3.2.13.RELEASE]->())) 
java.lang.Throwable: XmlFile null for virtualFile=null; artifact=org.springframework:spring-webmvc:jar:3.2.13.RELEASE->(org.springframework:spring-beans:jar:3.2.13.RELEASE->(org.springframework:spring-core:jar:3.2.13.RELEASE[DUPLICATE:org.springframework:spring-core:jar:3.2.13.RELEASE]->()),org.springframework:spring-context:jar:3.2.13.RELEASE->(org.springframework:spring-aop:jar:3.2.13.RELEASE->(aopalliance:aopalliance:jar:1.0->(),org.springframework:spring-beans:jar:3.2.13.RELEASE[DUPLICATE:org.springframework:spring-beans:jar:3.2.13.RELEASE]->(),org.springframework:spring-core:jar:3.2.13.RELEASE[DUPLICATE:org.springframework:spring-core:jar:3.2.13.RELEASE]->()),org.springframework:spring-beans:jar:3.2.13.RELEASE[DUPLICATE:org.springframework:spring-beans:jar:3.2.13.RELEASE]->(),org.springframework:spring-core:jar:3.2.13.RELEASE[DUPLICATE:org.springframework:spring-core:jar:3.2.13.RELEASE]->(),org.springframework:spring-expression:jar:3.2.13.RELEASE[DUPLICATE:org.springframework:spring-expression:jar:3.2.13.RELEASE]->()),org.springframework:spring-core:jar:3.2.13.RELEASE->(),org.springframework:spring-expression:jar:3.2.13.RELEASE->(org.springframework:spring-core:jar:3.2.13.RELEASE[DUPLICATE:org.springframework:spring-core:jar:3.2.13.RELEASE]->()),org.springframework:spring-web:jar:3.2.13.RELEASE->(org.springframework:spring-aop:jar:3.2.13.RELEASE[DUPLICATE:org.springframework:spring-aop:jar:3.2.13.RELEASE]->(),org.springframework:spring-beans:jar:3.2.13.RELEASE[DUPLICATE:org.springframework:spring-beans:jar:3.2.13.RELEASE]->(),org.springframework:spring-context:jar:3.2.13.RELEASE[DUPLICATE:org.springframework:spring-context:jar:3.2.13.RELEASE]->(),org.springframework:spring-core:jar:3.2.13.RELEASE[DUPLICATE:org.springframework:spring-core:jar:3.2.13.RELEASE]->()))
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:143)
	at krasa.mavenhelper.analyzer.action.BaseAction.getXmlFile(BaseAction.java:76)
	at krasa.mavenhelper.analyzer.action.BaseAction.getDomFileElement(BaseAction.java:56)
	at krasa.mavenhelper.analyzer.action.ExcludeDependencyAction.exclude(ExcludeDependencyAction.java:30)
	at krasa.mavenhelper.analyzer.action.ExcludeDependencyAction.access$000(ExcludeDependencyAction.java:20)
	at krasa.mavenhelper.analyzer.action.ExcludeDependencyAction$3$1.run(ExcludeDependencyAction.java:86)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:994)
	at krasa.mavenhelper.analyzer.action.ExcludeDependencyAction$3.run(ExcludeDependencyAction.java:84)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:220)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:177)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:167)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:153)
	at krasa.mavenhelper.analyzer.action.ExcludeDependencyAction.actionPerformed(ExcludeDependencyAction.java:82)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:295)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.lambda$actionPerformed$0(ActionMenuItem.java:296)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.runOnOwnContext(FocusManagerImpl.java:281)
	at com.intellij.openapi.wm.impl.IdeFocusManagerImpl.runOnOwnContext(IdeFocusManagerImpl.java:77)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.actionPerformed(ActionMenuItem.java:285)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1967)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.lambda$fireActionPerformed$0(ActionMenuItem.java:112)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:94)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.fireActionPerformed(ActionMenuItem.java:112)
	at com.intellij.ui.plaf.beg.BegMenuItemUI.doClick(BegMenuItemUI.java:517)
	at com.intellij.ui.plaf.beg.BegMenuItemUI.access$300(BegMenuItemUI.java:36)
	at com.intellij.ui.plaf.beg.BegMenuItemUI$MyMouseInputHandler.mouseReleased(BegMenuItemUI.java:539)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6632)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3342)
	at java.desktop/java.awt.Component.processEvent(Component.java:6397)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5008)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4840)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4547)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2772)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4840)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:965)
	at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.java:903)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:835)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:449)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:743)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:448)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:816)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:502)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
2020-05-29 20:28:13,047 [  41129]  ERROR - per.analyzer.action.BaseAction - IntelliJ IDEA 2020.2 EAP  Build #IU-202.4357.23 
2020-05-29 20:28:13,047 [  41129]  ERROR - per.analyzer.action.BaseAction - JDK: 11.0.3; VM: Java HotSpot(TM) 64-Bit Server VM; Vendor: Oracle Corporation 
2020-05-29 20:28:13,047 [  41129]  ERROR - per.analyzer.action.BaseAction - OS: Windows 10 
2020-05-29 20:28:13,047 [  41129]  ERROR - per.analyzer.action.BaseAction - Plugin to blame: Maven Helper version: 4.8.193.000.0 
2020-05-29 20:28:13,047 [  41129]  ERROR - per.analyzer.action.BaseAction - Current Command: Exclude 
```

**Comment by StephanPraetsch** [comment]
Here we go
```bash
stephan@lin-praetschs:~/.cache/JetBrains/IntelliJIdea2020.1/log> tail -f idea.log
```
after clicking on `exclude`:
```
2020-05-29 23:14:28,300 [  31177]  ERROR - per.analyzer.action.BaseAction - DomFileElement<MavenDomProjectModel> null for xmlFile=XmlFile:pom.xml 
java.lang.Throwable: DomFileElement<MavenDomProjectModel> null for xmlFile=XmlFile:pom.xml
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:146)
	at krasa.mavenhelper.analyzer.action.BaseAction.getDomFileElement(BaseAction.java:61)
	at krasa.mavenhelper.analyzer.action.ExcludeDependencyAction.exclude(ExcludeDependencyAction.java:30)
	at krasa.mavenhelper.analyzer.action.ExcludeDependencyAction.access$000(ExcludeDependencyAction.java:20)
	at krasa.mavenhelper.analyzer.action.ExcludeDependencyAction$3$1.run(ExcludeDependencyAction.java:86)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:976)
	at krasa.mavenhelper.analyzer.action.ExcludeDependencyAction$3.run(ExcludeDependencyAction.java:84)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:220)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:178)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:168)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:154)
	at krasa.mavenhelper.analyzer.action.ExcludeDependencyAction.actionPerformed(ExcludeDependencyAction.java:82)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:280)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.lambda$actionPerformed$0(ActionMenuItem.java:296)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.runOnOwnContext(FocusManagerImpl.java:281)
	at com.intellij.openapi.wm.impl.IdeFocusManagerImpl.runOnOwnContext(IdeFocusManagerImpl.java:77)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.actionPerformed(ActionMenuItem.java:285)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1967)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.lambda$fireActionPerformed$0(ActionMenuItem.java:112)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:94)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.fireActionPerformed(ActionMenuItem.java:112)
	at com.intellij.ui.plaf.beg.BegMenuItemUI.doClick(BegMenuItemUI.java:517)
	at com.intellij.ui.plaf.beg.BegMenuItemUI.access$300(BegMenuItemUI.java:36)
	at com.intellij.ui.plaf.beg.BegMenuItemUI$MyMouseInputHandler.mouseReleased(BegMenuItemUI.java:539)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6651)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3345)
	at java.desktop/java.awt.Component.processEvent(Component.java:6416)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5026)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4858)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4547)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2773)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4858)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:778)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:751)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:749)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:748)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:974)
	at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.java:912)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:844)
	at com.intellij.ide.IdeEventQueue.lambda$null$8(IdeEventQueue.java:449)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:741)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:448)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:831)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:502)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
2020-05-29 23:14:28,303 [  31180]  ERROR - per.analyzer.action.BaseAction - IntelliJ IDEA 2020.1.1  Build #IU-201.7223.91 
2020-05-29 23:14:28,303 [  31180]  ERROR - per.analyzer.action.BaseAction - JDK: 11.0.6; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o 
2020-05-29 23:14:28,303 [  31180]  ERROR - per.analyzer.action.BaseAction - OS: Linux 
2020-05-29 23:14:28,303 [  31180]  ERROR - per.analyzer.action.BaseAction - Plugin to blame: Maven Helper version: 4.8.193.000.1 
2020-05-29 23:14:28,303 [  31180]  ERROR - per.analyzer.action.BaseAction - Current Command: Exclude 
2020-05-29 23:14:28,385 [  31262]   WARN - ion.impl.NotificationCollector - Notification group 'System Messages' is already registered in whitelist 
2020-05-29 23:14:28,385 [  31262]   WARN - ion.impl.NotificationCollector - Notification group 'Project generator' is already registered in whitelist 
2020-05-29 23:14:28,385 [  31262]   WARN - ion.impl.NotificationCollector - Notification group 'Heap Dump Analysis' is already registered in whitelist 
2020-05-29 23:14:28,385 [  31262]   WARN - ion.impl.NotificationCollector - Notification group 'Low Memory' is already registered in whitelist 
2020-05-29 23:14:28,838 [  31715]   INFO - ateSettings.impl.UpdateChecker - failed to load plugin descriptions from : Malformed URL:  
2020-05-29 23:14:29,393 [  32270]   INFO - dea.updater.SdkComponentSource - Downloading https://dl.google.com/android/repository/addons_list-3.xml 
2020-05-29 23:14:29,802 [  32679]   INFO - dea.updater.SdkComponentSource - File /home/stephan/.android/repositories.cfg could not be loaded. 
2020-05-29 23:14:29,804 [  32681]   INFO - dea.updater.SdkComponentSource - Downloading https://dl.google.com/android/repository/sys-img/android/sys-img2-1.xml 
2020-05-29 23:14:29,806 [  32683]   INFO - dea.updater.SdkComponentSource - Downloading https://dl.google.com/android/repository/sys-img/android-automotive/sys-img2-1.xml 
2020-05-29 23:14:29,808 [  32685]   INFO - dea.updater.SdkComponentSource - Downloading https://dl.google.com/android/repository/sys-img/android-wear/sys-img2-1.xml 
2020-05-29 23:14:29,809 [  32686]   INFO - dea.updater.SdkComponentSource - Downloading https://dl.google.com/android/repository/sys-img/android-wear-cn/sys-img2-1.xml 
2020-05-29 23:14:29,809 [  32686]   INFO - dea.updater.SdkComponentSource - Downloading https://dl.google.com/android/repository/sys-img/android-tv/sys-img2-1.xml 
2020-05-29 23:14:29,809 [  32686]   INFO - dea.updater.SdkComponentSource - Downloading https://dl.google.com/android/repository/sys-img/google_apis/sys-img2-1.xml 
2020-05-29 23:14:29,810 [  32687]   INFO - dea.updater.SdkComponentSource - Downloading https://dl.google.com/android/repository/addon2-1.xml 
2020-05-29 23:14:29,810 [  32687]   INFO - dea.updater.SdkComponentSource - Downloading https://dl.google.com/android/repository/sys-img/google_apis_playstore/sys-img2-1.xml 
2020-05-29 23:14:29,812 [  32689]   INFO - dea.updater.SdkComponentSource - Downloading https://dl.google.com/android/repository/glass/addon2-1.xml 
2020-05-29 23:14:29,812 [  32689]   INFO - dea.updater.SdkComponentSource - Downloading https://dl.google.com/android/repository/repository2-1.xml 
2020-05-29 23:14:29,812 [  32689]   INFO - dea.updater.SdkComponentSource - Downloading https://dl.google.com/android/repository/extras/intel/addon2-1.xml 
```

**Comment by StephanPraetsch** [comment]
By the way: Why don't you use maven for your project? I would have liked to debug on my own and maybe contribute but your setup is quite tricky. Even if I succeed to setup I didn't know how to build a new version and test in my idea :(

**Comment by krasa** [comment]
I could use Gradle, but it is slow, maybe after this is fixed https://github.com/JetBrains/gradle-intellij-plugin/issues/459 ...

The setup is easy, even faster than with Gradle.

https://github.com/krasa/MavenHelper/blob/master/README.md#project-setup

**Comment by krasa** [comment]
It would be great if you could debug it. But I might just replace the pom finding logic. What I do on ~30 lines is currently done in the IntelliJ GUI diagram on 130 lines...

**Comment by StephanPraetsch** [comment]
Honestly I don't like to setup my own SDK by manually adding dependencies.That's what maven or gradle for. Nevertheless I've tried and failed. Probably missing a dependency I don't noticed:

1. configured a separate JDK with specific dependencies
![sdk](https://user-images.githubusercontent.com/9827763/83350433-6240ca80-a33c-11ea-859c-2216c8217d8b.png)
1. click on build that produces errors (here is already something wrong?)
![build](https://user-images.githubusercontent.com/9827763/83350446-7dabd580-a33c-11ea-9658-d76c7bd1c875.png)
1. add a new run configuration: does not show MavenHelper as an option but nothing
![plugin](https://user-images.githubusercontent.com/9827763/83350460-93b99600-a33c-11ea-8033-15df54a0be81.png)

**Comment by krasa** [comment]
Sure, but Maven would not work at all, and Gradle currently sucks. I made https://plugins.jetbrains.com/plugin/6844-useful-actions to not need to add jars manually.

Do this:
![image](https://user-images.githubusercontent.com/1160875/83350562-2d814300-a33d-11ea-922d-c47f8c7bd1d6.png)

Also do you have this enabled?
![image](https://user-images.githubusercontent.com/1160875/83350610-85b84500-a33d-11ea-8f2b-7aa18a6e25d5.png)

**Comment by krasa** [comment]
Your module seems to have a wrong type

![image](https://user-images.githubusercontent.com/1160875/83350771-b8167200-a33e-11ea-8515-cb7d8b8f4ecc.png)

**Comment by StephanPraetsch** [comment]
I've never done intellij plugin development. Just tried out [this tutorial](https://www.jetbrains.org/intellij/sdk/docs/tutorials/build_system/prerequisites.html) that ends in `Java heap space` error ...
![heap](https://user-images.githubusercontent.com/9827763/83351613-dcc21800-a345-11ea-94f4-da22be25f2b7.png)


If you say gradle sucks currently I must trust. But at which cost? More efficient developing after successful setup or unable to setup correctly. I'd rather wait 20s between changes than being unable to setup at all.

In comparison to your icon my module has the wrong type. How do I import that project so that intellij recognizes the correct type? I always import with File > New > Module from Existing Source > Create module from existing source > next serveral times.

**Comment by krasa** [comment]
`Java heap space` - you need to change gradle.preperties to a new gradle, 6.1 is bugged. 

You should not create a module at all. Project files (.ipr and /.idea) are committed, so it should just open without importing. 

If not, then you could import a module (.iml) directly. 
`Module from Existing Source` does not support different module types, so it is sometimes better to click on `New Module`.

**Comment by krasa** [comment]
What you waste on learning to setup the old way, you would waste on the new gradle way too. :-)

For example figuring out that you need to disable this, to speed up debugging:
![image](https://user-images.githubusercontent.com/1160875/83352175-185ee100-a34a-11ea-8991-cf7dc2824803.png)

**Comment by StephanPraetsch** [comment]
Only File > Open did the trick (with the manually setup JDK). Now I'm able to debug your plugin in a new instance of intellij. But in this new intellij instance there is a different behavior: exclude works well ...

How do I package current files (to a zip?) to install the new version into my "main" intellij?

**Comment by krasa** [comment]
https://user-images.githubusercontent.com/1160875/83349939-b6e24680-a338-11ea-9443-6a74b563655f.png
- then drag the zip into the editor


JRE could be the issue, that is one thing that speaks for Gradle. But I would expect that something else, perhaps some obscure settings causes it.

The best would be to remote debug your main IntelliJ instance from another one (perhaps another version).

**Comment by krasa** [comment]
You can easily setup JetBrains JDK:
from here: https://confluence.jetbrains.com/display/JBR/JetBrains+Runtime 
-> JBRSDK11
-> Files tab
-> https://bintray.com/jetbrains/intellij-jbr/download_file?file_path=jbrsdk-11_0_7-linux-x64-b931.3.tar.gz

- create JDK, then attach it to the IntelliJ Platform SDK

**Comment by StephanPraetsch** [comment]
I ran with jbrsdk8 and 11 and both worked.

I see that `com.intellij.util.xml.impl.DomManagerImpl` is used in failure and in success case.

Only chance I see (just as you do) is to remote debug my main intellij ... I use the ultimate edition. Do you think I can use the [community edition sources](https://github.com/JetBrains/intellij-community) for debugging?

**Comment by krasa** [comment]
You can, only some classes are obfuscated, you can check out the right tag and add it to the SDK's Sourcepath, but I found that it is only rarely necessary, build-in decompiler works great.

I would focus on `org.jetbrains.idea.maven.dom.MavenDomFileDescription#isMyFile`

**Comment by krasa** [comment]
You can also compare it to the diagram action `org.jetbrains.idea.maven.ext.uml.actions.MavenExcludeDependency` from `\plugins\maven-ext\lib\maven-ext.jar`

**Comment by StephanPraetsch** [comment]
Feels like reverse engineering:
```java
		XmlFile xmlFile = getXmlFile(mavenArtifactNode);
...
        FileType fileType = xmlFile.getFileType();
```

Success: `fileType=com.intellij.ide.highlighter.XmlFileType@1d8134cc`
Failure: `fileType=com.kukido.eclipser.EclipserFileType@1afe4558`

**Comment by krasa** [comment]
Oh, eclipser.... https://github.com/kukido/eclipser/issues/32

**Comment by StephanPraetsch** [comment]
Geeeeeeeeeeeeeeeeeeeeeeezzzzzzzzzz ......... Disabling eclipser solves this issue. The hell, thanx :+1:

**Comment by krasa** [comment]
Thanks to you, I will try to add some warning message.
