### ISSUE TITLE
cannot start after upgrading intellij idea community to 2020.2.3 

### ISSUE THREAD

**Issue by littleboyonearth** [krasa/MavenHelper#66]
![image](https://user-images.githubusercontent.com/19209493/97968198-4795e480-1df9-11eb-80d5-61c795c49393.png)

**Comment by littleboyonearth** [comment]
![image](https://user-images.githubusercontent.com/19209493/97968328-76ac5600-1df9-11eb-9d4e-372eaec876e2.png)

**Comment by krasa** [comment]
could you post the whole exception?

**Comment by appreciated** [comment]
Hello I am currently have the same issue. Here is the log:
```
java.lang.Throwable
	at com.intellij.diagnostic.LoadingState.logStateError(LoadingState.java:63)
	at com.intellij.diagnostic.LoadingState.checkOccurred(LoadingState.java:59)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstanceUncached(BaseComponentAdapter.kt:71)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstance(BaseComponentAdapter.kt:67)
	at com.intellij.serviceContainer.ComponentManagerImpl.doGetService(ComponentManagerImpl.kt:413)
	at com.intellij.serviceContainer.ComponentManagerImpl.getService(ComponentManagerImpl.kt:395)
	at com.intellij.ide.plugins.PluginUtil.getInstance(PluginUtil.java:11)
	at com.intellij.notification.NotificationGroup.<init>(NotificationGroup.kt:41)
	at com.intellij.notification.NotificationGroup.<init>(NotificationGroup.kt:27)
	at com.intellij.notification.NotificationGroup.<init>(NotificationGroup.kt:35)
	at com.intellij.notification.NotificationGroup.<init>(NotificationGroup.kt:35)
	at com.intellij.notification.NotificationGroup.<init>(NotificationGroup.kt)
	at krasa.mavenhelper.ApplicationComponent.<clinit>(ApplicationComponent.java:29)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:398)
	at com.intellij.serviceContainer.ComponentManagerImpl.registerComponent(ComponentManagerImpl.kt:287)
	at com.intellij.serviceContainer.ComponentManagerImpl.registerComponents(ComponentManagerImpl.kt:193)
	at com.intellij.serviceContainer.ComponentManagerImpl.registerComponents(ComponentManagerImpl.kt:157)
	at com.intellij.idea.ApplicationLoader$registerAppComponents$1.apply(ApplicationLoader.kt:102)
	at com.intellij.idea.ApplicationLoader$registerAppComponents$1.apply(ApplicationLoader.kt)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:642)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2073)
	at com.intellij.idea.ApplicationLoader$initApplication$2.accept(ApplicationLoader.kt:390)
	at com.intellij.idea.ApplicationLoader$initApplication$2.accept(ApplicationLoader.kt)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenCompleteStage(CompletableFuture.java:883)
	at java.base/java.util.concurrent.CompletableFuture.whenComplete(CompletableFuture.java:2251)
	at java.base/java.util.concurrent.CompletableFuture.whenComplete(CompletableFuture.java:143)
	at com.intellij.idea.ApplicationLoader.initApplication(ApplicationLoader.kt:387)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.intellij.idea.a.a(a.java:106)
	at com.intellij.ide.a.l.ab.a(ab.java:91)
	at com.intellij.ide.a.l.S.b(S.java:276)
	at com.intellij.ide.a.l.T.b(T.java:307)
	at com.intellij.ide.a.l.T.c(T.java:167)
	at com.intellij.ide.a.l.T.a(T.java:79)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.intellij.idea.MainImpl.start(MainImpl.java:98)
	at com.intellij.idea.StartupUtil.startApp(StartupUtil.java:302)
	at com.intellij.idea.StartupUtil.prepareApp(StartupUtil.java:242)
	at com.intellij.ide.plugins.MainRunner.lambda$start$0(MainRunner.java:47)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by krasa** [comment]
I see, you have a very old plugin version. Did you update from IntelliJ 2018?
 
I will configure it to not be enabled for newer IDEs, so it will be automatically disabled in the next IDE version.

**Comment by appreciated** [comment]
> I see, you have a very old plugin version. 

@krasa Thanks for the hint, this fixed the issue for me!

**Comment by krasa** [comment]
https://youtrack.jetbrains.com/issue/IDEA-254478

**Comment by littleboyonearth** [comment]
Yes, after upgrading to the latest version, it works all right!
Thanks a lot!
curious why intellij idea not upgrade automatically
