### ISSUE TITLE
Result idea UI fronzen with idea 2021.1 and wsl2 Ubuntu 20.04

### ISSUE THREAD

**Issue by EverySeptember** [krasa/MavenHelper#69]
my environment : idea 2021.1, wsl2 Ubuntu 20.04, idea bundled maven 
When I right click at project folder or file , the idea UI fronzed.
[threadDump-20210512-111008.txt](https://github.com/krasa/MavenHelper/files/6463353/threadDump-20210512-111008.txt)

Part of the log:
2021-05-12 11:06:45,483 [ 725922]   INFO - rationStore.ComponentStoreImpl - Saving appGeneralSettings took 12 ms, TodoConfiguration took 21 ms 
2021-05-12 11:08:08,964 [ 809403]   WARN - ctionSystem.impl.ActionUpdater - 80717ms to expand group child null 
2021-05-12 11:08:08,965 [ 809404]   WARN - ctionSystem.impl.ActionUpdater - 80719ms to expand group child null 
2021-05-12 11:08:08,965 [ 809404]   WARN - ctionSystem.impl.ActionUpdater - 80719ms to expand group child ProjectViewPopupMenuRunGroup 
2021-05-12 11:08:08,993 [ 809432]   WARN - penapi.actionSystem.impl.Utils - Skipping empty menu item for action  () of class org.intellij.lang.xpath.xslt.associations.impl.AssociationsGroup 
2021-05-12 11:08:08,995 [ 809434]   WARN - ystem.impl.ActionPopupMenuImpl - 80756ms to fill popup menu ProjectViewPopup 
2021-05-12 11:10:03,179 [ 923618]   WARN - ctionSystem.impl.ActionUpdater - 114177ms to expand group child null 
2021-05-12 11:10:03,181 [ 923620]   WARN - ctionSystem.impl.ActionUpdater - 114178ms to expand group child null 
2021-05-12 11:10:03,181 [ 923620]   WARN - ctionSystem.impl.ActionUpdater - 114179ms to expand group child ProjectViewPopupMenuRunGroup 
2021-05-12 11:10:03,217 [ 923656]   WARN - penapi.actionSystem.impl.Utils - Skipping empty menu item for action  () of class org.intellij.lang.xpath.xslt.associations.impl.AssociationsGroup 
2021-05-12 11:10:03,499 [ 923938]   WARN - .diagnostic.PerformanceWatcher - UI was frozen for 195060ms, details saved to C:\Users\lu\AppData\Local\JetBrains\IdeaIC2021.1\log\threadDumps-freeze-20210512-110653-IC-211.7142.45-195sec 
2021-05-12 11:10:03,895 [ 924334]   INFO - rationStore.ComponentStoreImpl - Saving appP3cConfig took 13 ms 
2021-05-12 11:10:10,395 [ 930834]   INFO - mponents.impl.stores.StoreUtil - saveProjectsAndApp took 6563 ms 
2021-05-12 11:10:10,402 [ 930841]   WARN - .diagnostic.PerformanceWatcher - UI was frozen for 6467ms, details saved to C:\Users\lu\AppData\Local\JetBrains\IdeaIC2021.1\log\threadDumps-freeze-20210512-111008-IC-211.7142.45-6sec 
[threadDump-20210512-111008.txt](https://github.com/krasa/MavenHelper/files/6463351/threadDump-20210512-111008.txt)

**Comment by krasa** [comment]
I do not see tthis plugin in the threaddump, but only `at com.baomidou.plugin.idea.mybatisx.inspection.MapperXmlInspection.checkDomElement(MapperXmlInspection.java:27)`

**Comment by EverySeptember** [comment]
I tried again after uninstalling com.baomidou.plugin.idea.mybatisx,but it still does not work.
Here is the new log :
2021-05-12 13:41:05,943 [ 131656]   INFO - rationStore.ComponentStoreImpl - Saving appCodeStyleSchemeSettings took 18 ms, FileTypeManager took 20 ms, GraziConfig took 14 ms, MavenRunHelper took 35 ms 
2021-05-12 13:42:17,205 [ 202918]   WARN - ctionSystem.impl.ActionUpdater - 62173ms to expand group child null 
2021-05-12 13:42:17,209 [ 202922]   WARN - ctionSystem.impl.ActionUpdater - 62185ms to expand group child null 
2021-05-12 13:42:17,209 [ 202922]   WARN - ctionSystem.impl.ActionUpdater - 62187ms to expand group child ProjectViewPopupMenuRunGroup 
2021-05-12 13:42:17,305 [ 203018]   WARN - penapi.actionSystem.impl.Utils - Skipping empty menu item for action  () of class org.intellij.lang.xpath.xslt.associations.impl.AssociationsGroup 
2021-05-12 13:42:17,332 [ 203045]   WARN - ystem.impl.ActionPopupMenuImpl - 62575ms to fill popup menu ProjectViewPopup 
2021-05-12 13:43:27,314 [ 273027]   WARN - ctionSystem.impl.ActionUpdater - 69967ms to expand group child null 
2021-05-12 13:43:27,315 [ 273028]   WARN - ctionSystem.impl.ActionUpdater - 69968ms to expand group child null 
2021-05-12 13:43:27,316 [ 273029]   WARN - ctionSystem.impl.ActionUpdater - 69968ms to expand group child ProjectViewPopupMenuRunGroup 
2021-05-12 13:43:27,341 [ 273054]   WARN - penapi.actionSystem.impl.Utils - Skipping empty menu item for action  () of class org.intellij.lang.xpath.xslt.associations.impl.AssociationsGroup 
2021-05-12 13:43:27,473 [ 273186]   WARN - .diagnostic.PerformanceWatcher - UI was frozen for 132701ms, details saved to C:\Users\lu\AppData\Local\JetBrains\IdeaIC2021.1\log\threadDumps-freeze-20210512-134119-IC-211.7142.45-132sec 
2021-05-12 13:43:28,471 [ 274184]  ERROR -    #com.intellij.DynamicBundle - class com.intellij.DynamicBundle$LanguageBundleEP cannot be cast to class com.intellij.DynamicBundle$LanguageBundleEP (com.intellij.DynamicBundle$LanguageBundleEP is in unnamed module of loader com.intellij.util.lang.PathClassLoader @36b4cef0; com.intellij.DynamicBundle$LanguageBundleEP is in unnamed module of loader com.intellij.ide.plugins.cl.PluginClassLoader @18da7ba1) 
java.lang.ClassCastException: class com.intellij.DynamicBundle$LanguageBundleEP cannot be cast to class com.intellij.DynamicBundle$LanguageBundleEP (com.intellij.DynamicBundle$LanguageBundleEP is in unnamed module of loader com.intellij.util.lang.PathClassLoader @36b4cef0; com.intellij.DynamicBundle$LanguageBundleEP is in unnamed module of loader com.intellij.ide.plugins.cl.PluginClassLoader @18da7ba1)
	at com.intellij.DynamicBundle.findLanguageBundle(DynamicBundle.java:82)
	at com.intellij.DynamicBundle.findBundle(DynamicBundle.java:36)
	at com.intellij.AbstractBundle.resolveResourceBundle(AbstractBundle.java:146)
	at com.intellij.AbstractBundle.getResourceBundle(AbstractBundle.java:116)
	at com.intellij.AbstractBundle.getMessage(AbstractBundle.java:43)
	at org.jetbrains.kotlin.idea.KotlinIdeaAnalysisBundle$lazyMessage$1.invoke(KotlinIdeaAnalysisBundle.kt:27)
	at org.jetbrains.kotlin.idea.KotlinIdeaAnalysisBundle$lazyMessage$1.invoke(KotlinIdeaAnalysisBundle.kt:15)
	at org.jetbrains.kotlin.idea.intentions.SelfTargetingIntention.getFamilyName(SelfTargetingIntention.kt:53)
	at com.intellij.codeInsight.intention.impl.config.IntentionActionWrapper.getFamilyName(IntentionActionWrapper.java:54)
	at com.intellij.codeInsight.intention.impl.config.IntentionActionMetaData.getFamily(IntentionActionMetaData.java:44)
	at com.intellij.codeInsight.intention.impl.config.IntentionManagerSettings.registerMetaDataForEp(IntentionManagerSettings.java:93)
	at com.intellij.codeInsight.intention.impl.config.IntentionManagerSettings.lambda$new$0(IntentionManagerSettings.java:53)
	at com.intellij.openapi.extensions.impl.ExtensionProcessingHelper.forEachExtensionSafe(ExtensionProcessingHelper.java:34)
	at com.intellij.openapi.extensions.ExtensionPointName.forEachExtensionSafe(ExtensionPointName.java:46)
	at com.intellij.codeInsight.intention.impl.config.IntentionManagerSettings.<init>(IntentionManagerSettings.java:53)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at com.intellij.serviceContainer.ConstructorInjectionKt.instantiateUsingPicoContainer(constructorInjection.kt:47)
	at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClassWithConstructorInjection(ComponentManagerImpl.kt:771)
	at com.intellij.serviceContainer.ServiceComponentAdapter.createAndInitialize(ServiceComponentAdapter.kt:49)
	at com.intellij.serviceContainer.ServiceComponentAdapter.access$createAndInitialize(ServiceComponentAdapter.kt:13)
	at com.intellij.serviceContainer.ServiceComponentAdapter$doCreateInstance$1.run(ServiceComponentAdapter.kt:43)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:688)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:634)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:64)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeNonCancelableSection(CoreProgressManager.java:218)
	at com.intellij.serviceContainer.ServiceComponentAdapter.doCreateInstance(ServiceComponentAdapter.kt:42)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstanceUncached(BaseComponentAdapter.kt:110)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstance(BaseComponentAdapter.kt:64)
	at com.intellij.serviceContainer.ComponentManagerImpl.doGetService(ComponentManagerImpl.kt:488)
	at com.intellij.serviceContainer.ComponentManagerImpl.getService(ComponentManagerImpl.kt:471)
	at com.intellij.codeInsight.intention.impl.config.IntentionManagerSettings.getInstance(IntentionManagerSettings.java:105)
	at com.intellij.codeInsight.intention.impl.config.IntentionManagerImpl.getAvailableIntentions(IntentionManagerImpl.java:206)
	at com.intellij.codeInsight.daemon.impl.ShowIntentionsPass.getActionsToShow(ShowIntentionsPass.java:330)
	at com.intellij.codeInsight.daemon.impl.ShowIntentionsPass.doCollectInformation(ShowIntentionsPass.java:240)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:56)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$1(PassExecutorService.java:400)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1096)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:393)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:688)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:634)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:64)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:392)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:368)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:167)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:178)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:366)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:188)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
2021-05-12 13:43:28,473 [ 274186]  ERROR -    #com.intellij.DynamicBundle - IntelliJ IDEA 2021.1.1  Build #IC-211.7142.45 
2021-05-12 13:43:28,473 [ 274186]  ERROR -    #com.intellij.DynamicBundle - JDK: 11.0.10; VM: Dynamic Code Evolution 64-Bit Server VM; Vendor: JetBrains s.r.o. 
2021-05-12 13:43:28,473 [ 274186]  ERROR -    #com.intellij.DynamicBundle - OS: Windows 10 
2021-05-12 13:43:28,474 [ 274187]  ERROR -    #com.intellij.DynamicBundle - Plugin to blame: Kotlin version: 211-1.5.0-release-759-IJ6693.72 
2021-05-12 13:43:28,474 [ 274187]  ERROR -    #com.intellij.DynamicBundle - Last Action:  
2021-05-12 13:43:28,592 [ 274305]  ERROR -    #com.intellij.DynamicBundle - class com.intellij.DynamicBundle$LanguageBundleEP cannot be cast to class com.intellij.DynamicBundle$LanguageBundleEP (com.intellij.DynamicBundle$LanguageBundleEP is in unnamed module of loader com.intellij.util.lang.PathClassLoader @36b4cef0; com.intellij.DynamicBundle$LanguageBundleEP is in unnamed module of loader com.intellij.ide.plugins.cl.PluginClassLoader @18da7ba1) 
java.lang.ClassCastException: class com.intellij.DynamicBundle$LanguageBundleEP cannot be cast to class com.intellij.DynamicBundle$LanguageBundleEP (com.intellij.DynamicBundle$LanguageBundleEP is in unnamed module of loader com.intellij.util.lang.PathClassLoader @36b4cef0; com.intellij.DynamicBundle$LanguageBundleEP is in unnamed module of loader com.intellij.ide.plugins.cl.PluginClassLoader @18da7ba1)
	at com.intellij.DynamicBundle.findLanguageBundle(DynamicBundle.java:82)
	at com.intellij.DynamicBundle.findBundle(DynamicBundle.java:36)
	at com.intellij.AbstractBundle.resolveResourceBundle(AbstractBundle.java:146)
	at com.intellij.AbstractBundle.getResourceBundle(AbstractBundle.java:116)
	at com.intellij.AbstractBundle.getMessage(AbstractBundle.java:43)
	at org.jetbrains.kotlin.idea.maven.KotlinMavenBundle.message(KotlinMavenBundle.kt:19)
	at org.jetbrains.kotlin.idea.maven.actions.MavenPluginSourcesMoveToBuild.getFamilyName(MavenPluginSourcesSwap.kt:99)
	at com.intellij.codeInsight.intention.impl.config.IntentionActionWrapper.getFamilyName(IntentionActionWrapper.java:54)
	at com.intellij.codeInsight.intention.impl.config.IntentionActionMetaData.getFamily(IntentionActionMetaData.java:44)
	at com.intellij.codeInsight.intention.impl.config.IntentionManagerSettings.registerMetaDataForEp(IntentionManagerSettings.java:93)
	at com.intellij.codeInsight.intention.impl.config.IntentionManagerSettings.lambda$new$0(IntentionManagerSettings.java:53)
	at com.intellij.openapi.extensions.impl.ExtensionProcessingHelper.forEachExtensionSafe(ExtensionProcessingHelper.java:34)
	at com.intellij.openapi.extensions.ExtensionPointName.forEachExtensionSafe(ExtensionPointName.java:46)
	at com.intellij.codeInsight.intention.impl.config.IntentionManagerSettings.<init>(IntentionManagerSettings.java:53)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at com.intellij.serviceContainer.ConstructorInjectionKt.instantiateUsingPicoContainer(constructorInjection.kt:47)
	at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClassWithConstructorInjection(ComponentManagerImpl.kt:771)
	at com.intellij.serviceContainer.ServiceComponentAdapter.createAndInitialize(ServiceComponentAdapter.kt:49)
	at com.intellij.serviceContainer.ServiceComponentAdapter.access$createAndInitialize(ServiceComponentAdapter.kt:13)
	at com.intellij.serviceContainer.ServiceComponentAdapter$doCreateInstance$1.run(ServiceComponentAdapter.kt:43)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:688)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:634)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:64)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeNonCancelableSection(CoreProgressManager.java:218)
	at com.intellij.serviceContainer.ServiceComponentAdapter.doCreateInstance(ServiceComponentAdapter.kt:42)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstanceUncached(BaseComponentAdapter.kt:110)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstance(BaseComponentAdapter.kt:64)
	at com.intellij.serviceContainer.ComponentManagerImpl.doGetService(ComponentManagerImpl.kt:488)
	at com.intellij.serviceContainer.ComponentManagerImpl.getService(ComponentManagerImpl.kt:471)
	at com.intellij.codeInsight.intention.impl.config.IntentionManagerSettings.getInstance(IntentionManagerSettings.java:105)
	at com.intellij.codeInsight.intention.impl.config.IntentionManagerImpl.getAvailableIntentions(IntentionManagerImpl.java:206)
	at com.intellij.codeInsight.daemon.impl.ShowIntentionsPass.getActionsToShow(ShowIntentionsPass.java:330)
	at com.intellij.codeInsight.daemon.impl.ShowIntentionsPass.doCollectInformation(ShowIntentionsPass.java:240)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:56)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$1(PassExecutorService.java:400)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1096)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:393)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:688)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:634)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:64)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:392)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:368)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:167)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:178)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:366)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:188)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
2021-05-12 13:43:28,593 [ 274306]  ERROR -    #com.intellij.DynamicBundle - IntelliJ IDEA 2021.1.1  Build #IC-211.7142.45 
2021-05-12 13:43:28,594 [ 274307]  ERROR -    #com.intellij.DynamicBundle - JDK: 11.0.10; VM: Dynamic Code Evolution 64-Bit Server VM; Vendor: JetBrains s.r.o. 
2021-05-12 13:43:28,594 [ 274307]  ERROR -    #com.intellij.DynamicBundle - OS: Windows 10 
2021-05-12 13:43:28,599 [ 274312]  ERROR -    #com.intellij.DynamicBundle - Plugin to blame: Kotlin version: 211-1.5.0-release-759-IJ6693.72 
2021-05-12 13:43:28,600 [ 274313]  ERROR -    #com.intellij.DynamicBundle - Last Action:  

[threadDumps-freeze-20210512-134119-IC-211.7142.45-132sec.zip](https://github.com/krasa/MavenHelper/files/6463761/threadDumps-freeze-20210512-134119-IC-211.7142.45-132sec.zip)

**Comment by krasa** [comment]
Now I see it
```
"AWT-EventQueue-0" prio=0 tid=0x0 nid=0x0 waiting on condition
     java.lang.Thread.State: TIMED_WAITING
 on com.intellij.util.concurrency.Semaphore$Sync@493f5dab
	at java.base@11.0.10/jdk.internal.misc.Unsafe.park(Native Method)
	at java.base@11.0.10/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:234)
	at java.base@11.0.10/java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedNanos(AbstractQueuedSynchronizer.java:1079)
	at java.base@11.0.10/java.util.concurrent.locks.AbstractQueuedSynchronizer.tryAcquireSharedNanos(AbstractQueuedSynchronizer.java:1369)
	at com.intellij.util.concurrency.Semaphore.waitForUnsafe(Semaphore.java:97)
	at com.intellij.util.concurrency.Semaphore.waitFor(Semaphore.java:87)
	at com.intellij.execution.process.ProcessHandler.waitFor(ProcessHandler.java:105)
	at com.intellij.execution.process.BaseOSProcessHandler.waitFor(BaseOSProcessHandler.java:199)
	at com.intellij.execution.process.OSProcessHandler.waitFor(OSProcessHandler.java:119)
	at com.intellij.execution.process.CapturingProcessRunner.runProcess(CapturingProcessRunner.java:61)
	at com.intellij.execution.process.CapturingProcessRunner.runProcess(CapturingProcessRunner.java:50)
	at com.intellij.execution.process.CapturingProcessHandler.runProcess(CapturingProcessHandler.java:64)
	at com.intellij.execution.wsl.WSLDistribution.executeOnWsl(WSLDistribution.java:136)
	at com.intellij.execution.wsl.WSLDistribution.getEnvironment(WSLDistribution.java:412)
	at org.jetbrains.idea.maven.utils.MavenWslUtil.resolveMavenHomeDirectory(MavenWslUtil.kt:88)
	at org.jetbrains.idea.maven.utils.MavenWslUtil.resolveGlobalSettingsFile(MavenWslUtil.kt:58)
	at org.jetbrains.idea.maven.utils.MavenWslUtil.resolveLocalRepository(MavenWslUtil.kt:142)
	at org.jetbrains.idea.maven.project.MavenProjectsManager.getLocalRepository(MavenProjectsManager.java:216)
	at krasa.mavenhelper.action.MainMavenActionGroup.addPluginGoals(MainMavenActionGroup.java:184)
	at krasa.mavenhelper.action.MainMavenActionGroup.getPlugins(MainMavenActionGroup.java:168)
	at krasa.mavenhelper.action.MainMavenActionGroup.getActions(MainMavenActionGroup.java:69)
	at krasa.mavenhelper.action.MainMavenActionGroup.getChildren(MainMavenActionGroup.java:51)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$new$3(ActionUpdater.java:108)
```

**Comment by EverySeptember** [comment]
oh , one more thing , my idea is community version

**Comment by krasa** [comment]
Thanks! You can try it:
[MavenRunHelper.zip](https://github.com/krasa/MavenHelper/files/6463828/MavenRunHelper.zip)
(drop it into a text editor or use File | Settings | Plugins to install)

**Comment by krasa** [comment]
Could you also try if this autocomplete freezes? 
![image](https://user-images.githubusercontent.com/1160875/117927925-27d8ff00-b2fb-11eb-89c0-24b92bd4d93a.png)

**Comment by krasa** [comment]
There is some problem with WSL https://youtrack.jetbrains.com/issues/IDEA?q=%22org.jetbrains.idea.maven.project.MavenProjectsManager.getLocalRepository%22

**Comment by EverySeptember** [comment]
Thanks, it works on project right click, and the autocomplete frozed yet.

**Comment by krasa** [comment]
you could try this: https://youtrack.jetbrains.com/issue/IDEA-266289#focus=Comments-27-4871715.0-0

**Comment by EverySeptember** [comment]
Thanks, i have finished reading it. So we need to wait for the IDEA upgrade to solve this problem, right?

**Comment by krasa** [comment]
Yes.
